baseURL = "http://sparalic.github.io/"
languageCode = "en-us"
title = "Sparkle Russell-Puleri"
theme = "gohugo-theme-ananke"
tags = ["Deep Learning", "Machine Learning","blog"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsStyle = "monokai"

[sitemap]
  changefreq = "daily"
  priority = 0.9
  filename = "sitemap.xml"

[params]
  avatar = "images/Sparkle.png"
  favicon = ""
  description = "Land of the Humming Bird"
  facebook = ""
  twitter = "https://twitter.com/sparklepuleri"
  instagram = ""
  youtube = ""
  github = "https://github.com/sparalic"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/sparkle-russell-puleri-ph-d-a6b52643/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hb.jpeg"
  recent_posts_number = 2

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "sparklepuleri"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "sparalic"
    gplus     = ""

